In [34]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

Neste notebook a técnica K-Fold Cross Validation é aplicada. Os dados utilizados são do próprio sklearn: digits database. 
A técnica de cross validation abordada é aplicada para três modelos distintos: Logistic Regression, Support Vector Machine e Random Forest.

Inicialmente a utilização do train_test_split é ilustrada.

## Aplicação de modelos de Machine Learning

train_test_split

In [35]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size =0.3)

In [36]:
type(X_test)

numpy.ndarray

In [37]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

/home/yorinori/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9592592592592593

Como o modelo foi incapaz de convergir para o número de iterações default, foi necessário modificar o número de iterações limite como mostrado a seguir:

In [38]:
lr = LogisticRegression(max_iter=10000)
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9648148148148148

In [39]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.987037037037037

In [40]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9685185185185186

In [41]:
from sklearn.model_selection import KFold
N_splits = 3  #It's 3 just for example purposes, 10 is a great value
kf = KFold(n_splits=N_splits)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [42]:
for train_index, test_index in kf.split([1, 2, 3, 4, 5, 6, 7, 8, 9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [43]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [44]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=N_splits)

In [45]:
scores_l = []
scores_svm = []
scores_rf = []

for train_index, test_index in kf.split(digits.data):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_l.append(get_score(LogisticRegression(max_iter=10000), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test))

A seguir mostramos uma lista para o score de cada método em cada uma das iterações

In [46]:
scores_l

[0.9282136894824707, 0.9415692821368948, 0.9165275459098498]

In [47]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [48]:
scores_rf

[0.9415692821368948, 0.9565943238731218, 0.9248747913188647]

O que foi feito acima faz parte de uma função bult-in do sklearn e sua utilização é demonstrada a seguir:

In [49]:
from sklearn.model_selection import cross_val_score

In [54]:
cross_val_score(LogisticRegression(max_iter=10000), digits.data, digits.target)

array([0.92222222, 0.87777778, 0.93871866, 0.93314763, 0.89693593])

In [55]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [56]:
cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target)

array([0.91944444, 0.90277778, 0.95264624, 0.95264624, 0.91922006])